app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/



Route::get('/', ,  function () {
    
    return view('auth.login', true);

});

Route::group(['prefix' => 'admin' ,'middleware' => 'auth'], function () {
    
   Route::resource('users','UsersController');
   Route::get('users/{id}/destroy', 
   	[ 'uses' => 'UsersController@destroy',
   	'as' => 'admin.users.destroy']);
});






Route::resource('comercial','ComercialController', ['except' => ['show']]);

 Route::resource('solicitud','SolicitudController');


   Route::group(['prefix' => 'comercial','middleware' => 'auth'], function () {
 $exitCode = Artisan::call('cache:clear');

    Route::resource('ofertasposiblesclientes','Ofertaspccontroller');
   Route::resource('creacion_de_clientes','CreacionController');
   
   Route::resource('ofertas','Ofertascontroller',['except' => ['show']]);
   Route::get('comercial/{id}/destroy', 
   	[ 'uses' => 'Ofertascontroller@destroy',
   	'as' => 'Comercial.ofertas.destroy']);
   Route::resource('clientes','ClientesController',['except' => ['show']]);

   


  



});

// Route::group(['prefix' => 'comercial' ,'middleware' => 'auth'], function () {
    
//    Route::resource('clientes','ClientesController');
//    Route::get('clientes/{identificacion}/destroy', 
//       [ 'uses' => 'ClientesController@destroy',
//       'as' => 'comercial.clientes.destroy']);
// });



    


Route::auth();

Route::get('/home', 'HomeController@index');

Route::filter('forcehttps', function()
{
  if(!Request::secure())
  {
    return Redirect::secure(Request::getRequestUri(),301);
  }
});

routes/web.php
<?php
use Illuminate\Support\Facades\Input;
use App\cliente;
use App\sedes;

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


Route::get('/', array('http', function () {

    if(Auth::guest())
    {
    return view('auth.login');
    }

    else{

    
        $identificacion = auth()->user()->identificacion;

        if (auth()->user()->type == 'cliente' && auth()->user()->lastlogin !== '0000-00-00 00:00:00') {
             auth()->user()->lastlogin = new DateTime();
            auth()->user()->save();

           return route('cliente', $identificacion);
        }

        elseif(auth()->user()->type == 'cliente'){

             auth()->user()->lastlogin = new DateTime();
        auth()->user()->save();

            Flash::warning('Por favor cambie la contraseña en la etiqueta usuarios contraseña. Muchas gracias por confiar en nosotros');    
            return route('cliente.edit', $identificacion);

        }

        if (auth()->user()->type == 'comercial') {
            return redirect('/comercial');
             auth()->user()->lastlogin = new DateTime();
            auth()->user()->save();
        }

        if (auth()->user()->type == 'gerenciaadmin') {
            return redirect ('/geradmin');
             auth()->user()->lastlogin = new DateTime();
            auth()->user()->save();
        }

        $iduser = auth()->user()->id;
        if (auth()->user()->type == 'ejdecuenta') {
            auth()->user()->lastlogin = new DateTime();
            auth()->user()->save();
           return route('ejdecuenta', $iduser);
        }

        $iduser = auth()->user()->id;
        if (auth()->user()->type == 'facturacion') {
            auth()->user()->lastlogin = new DateTime();
            auth()->user()->save();
            return redirect('/facturacion');    
        }

        $iduser = auth()->user()->id;
        if (auth()->user()->type == 'posconsumos') {
            auth()->user()->lastlogin = new DateTime();
            auth()->user()->save();
            return redirect('/pos');    
        }
   
    }

}));



Route::resource('pos','Posconsumos\PosController', ['middleware' => ['auth', 'posconsumos'],'except' => ['show']]);

Route::group(['prefix' => 'posconsumos','middleware' => ['auth', 'posconsumos']], function () {

    Route::get('/lumina/{id}/pdf', 
    [ 'uses' => 'Posconsumos\LuminaController@certpdf',
    'as' => 'lumina.pdf.generate']);

    Route::get('/lumina/almc/{id}/pdf', 
    [ 'uses' => 'Posconsumos\LuminaController@certalmcpdf',
    'as' => 'lumina.pdf.almc.generate']);

    Route::get('/lumina/almc/{id}/pdf/down', 
    [ 'uses' => 'Posconsumos\LuminaController@certalmcpdfdown',
    'as' => 'lumina.pdf.almc.down']);

    Route::get('/lumina/almc/{id}/pdf/download', 
    [ 'uses' => 'Posconsumos\LuminaController@certalmcpdfdownload',
    'as' => 'lumina.pdf.almc.generate.download']);

Route::post('import', 'Posconsumos\GestoresController@import')->name('gestores.import');


Route::post('import', 'Posconsumos\GestoresController@import')->name('gestores.import');



Route::get('export', 'Posconsumos\GestoresController@export')->name('gestores.export');

    Route::resource('lumina','Posconsumos\LuminaController');
    Route::post('lumina/update', 
    [ 'uses' => 'Posconsumos\LuminaController@update',   
    'as' => 'lumina.update']);
    

    Route::resource('generadores','Posconsumos\GeneradoresController');

    Route::get('exportgen', 'Posconsumos\GeneradoresController@export')->name('generadores.export');

    Route::post('importgen', 'Posconsumos\GeneradoresController@import')->name('generadores.import');

    Route::resource('gestores','Posconsumos\GestoresController');

    Route::get('/autocompletegen',array('as'=>'autocompletegen','uses'=>'Posconsumos\LuminaController@autocompletegen'));

    Route::get('/autocompleteges',array('as'=>'autocompleteges','uses'=>'Posconsumos\LuminaController@autocompleteges'));

    Route::get('/autocompletecanal',array('as'=>'autocompletecanal','uses'=>'Posconsumos\LuminaController@autocompletecanal'));



    });

Route::resource('facturacion','Facturacion\FacturacionController', ['middleware' => ['auth', 'facturacion'],'except' => ['show']]);
Route::group(['prefix' => 'facturacion','middleware' => ['auth', 'facturacion']], function () {

    Route::resource('remisiones','Facturacion\RemisionController', ['middleware' => ['auth', 'facturacion']]);

    Route::get('/autocompleteser',array('as'=>'facturacion.autocompleteser','uses'=>'Facturacion\RemisionController@autocompleteser'));
    Route::get('/autocompleter',array('as'=>'facturacion.autocompleter','uses'=>'Facturacion\RemisionController@autocompleter'));

    Route::get('{id}/pdf', 
    [ 'uses' => 'Facturacion\RemisionController@certpdf',
    'as' => 'cert.pdf']);

    Route::get('certpeligrosos/{id}/{identificacion}/pdf', 
    [ 'uses' => 'Facturacion\RemisionController@certpeligrosospdf',
    'as' => 'facturacion.certpeligrosospdf.pdf']);

    Route::put('certpeligrosos/{id}/upload', 
    [ 'uses' => 'Facturacion\FilescertController@store',
    'as' => 'facturacion.certpeligrosos.up']);

});


// Rutas ejdecuenta
Route::group(['prefix' => 'ejdecuenta','middleware' => ['auth', 'ejdecuenta']], function () {


    
    Route::resource('visitasejdecuenta','VisitasEjdecuentaController',['except' => ['show']]);

    Route::get('/visitas/{idvisita}', 
    [ 'uses' => 'VisitasEjdecuentaController@view',
    'as' => 'ejdecuenta.visitas.view']);

    Route::get('/{iduser}', 
    [ 'uses' => 'ejdecuenta@index',
    'as' => 'ejdecuenta']);

     Route::resource('ofertasejdecuenta','OfertasEjdecuentaController',['except' => ['show']]);

    Route::get('ofertasejdecuenta/create/{iduser}', 
    [ 'uses' => 'OfertasEjdecuentaController@create',   
    'as' => 'ofertasejdecuenta.create']); 

    Route::get('ofertasejdecuenta/index/{iduser}', 
    [ 'uses' => 'OfertasEjdecuentaController@index',   
    'as' => 'ofertasejdecuenta.index']);

    Route::get('{id}/{iduser}/pdf', 
    [ 'uses' => 'PdfControllerEjdecuenta@ofertapcpdf',
    'as' => 'ofertasejdecuenta.pdf']); 

    Route::get('{id}/{iduser}/pdf/download', 
    [ 'uses' => 'PdfControllerEjdecuenta@ofertapcpdfdownload',
    'as' => 'ofertasejdecuenta.pdf.download']);
    
    Route::get('/{id}/mail', 
    [ 'uses' => 'PdfController@mail',
    'as' => 'ofertasejdecuenta.mail']);

    Route::get('clientes/view', 
    [ 'uses' => 'ClientesEjdecuentaController@index',   
    'as' => 'clientes.ejdecuenta.index']);

    Route::get('clientes/edit/{identificacion}', 
    [ 'uses' => 'ClientesEjdecuentaController@edit',   
    'as' => 'ejdecuenta.clientes.edit']);

    Route::put('clientes/update/{identificacion}', 
    [ 'uses' => 'ClientesEjdecuentaController@update',   
    'as' => 'ejdecuenta.clientes.update']);

    Route::get('clientes/show/{identificacion}', 
    [ 'uses' => 'ClientesEjdecuentaController@show',   
    'as' => 'ejdecuenta.clientes.show']);

    Route::put('/{identificacion}/files', 
    [ 'uses' => 'CreacionController@storecomercial',
    'as' => 'ejdecuenta.clientes.files.store']);

    Route::get('clientes/sedes/{sede}/eliminar', 
    [ 'uses' => 'ClientesEjdecuentaController@borrarsede',
    'as' => 'ejdecuenta.clientes.sedes.borrar']);

    Route::post('clientes/sedes/guardar', 
    [ 'uses' => 'ClientesEjdecuentaController@save',    
    'as' => 'ejdecuenta.clientes.sedes.save']);

    Route::get('clientes/sedes/{id}/{identificacion}/editar', 
    [ 'uses' => 'ClientesEjdecuentaController@editsede',    
    'as' => 'ejdecuenta.clientes.sedes.edit']);

    

    Route::put('clientes/sedes/update/{id}/{identificacion}', 
    [ 'uses' => 'ClientesEjdecuentaController@updatesede',
    'as' => 'ejdecuenta.clientes.sedes.update']);




      Route::get('uploadedFile/{filename}',['uses' => 'CreacionController@getFile',
    'as' => 'ejdecuenta.viewfiles']);

   Route::get('uploadedFile/{filename}/delete',['uses' => 'CreacionController@deleteFile',
    'as' => 'ejdecuenta.deletefiles']);

   Route::get('uploadedFile/{filename}/residuos',['uses' => 'ResiduosController@getFile',
    'as' => 'ejdecuenta.viewfilesresiduos']);

   Route::get('uploadedFile/{filename}/residuos/delete',['uses' => 'ResiduosController@deleteFile',
    'as' => 'ejdecuenta.deletefilesresiduos']);

   Route::get('clientes/creacion/{identificacion}', 
    [ 'uses' => 'ClientesEjdecuentaController@creacion',
    'as' => 'ejdecuenta.clientes.creacion']);
   Route::put('clientes/creacion/{identificacion}/actualizar', 
    [ 'uses' => 'ClientesEjdecuentaController@up',
    'as' => 'ejdecuenta.clientes.creacion.up']);
        // Rutas edición productos

       // rutas peligrosos

         Route::resource('peligrosos','Peligrososcontroller',['except' => ['show']]);
            Route::put('{id}/peligrosos', 
            [ 'uses' => 'OfertasEjdecuentaController@peligrosos',
            'as' => 'ejdecuenta.peligrosos']);


            Route::get('peligrosos/{idoferta}/{idpeligroso}/eliminar', 
            [ 'uses' => 'OfertasEjdecuentaController@borrarp',
            'as' => 'ejdecuenta.peligrosos.borrar']);

    
            // rutas aprovechables

            Route::resource('aprovechables','Aprovechablescontroller',['except' => ['show']]);
            Route::put('{id}/aprovechables', 
            [ 'uses' => 'OfertasEjdecuentaController@aprovechables',
            'as' => 'ejdecuenta.aprovechables']);
            

            Route::get('/{idoferta}/{idaprovechables}/aprovechables/eliminar', 
            [ 'uses' => 'OfertasEjdecuentaController@borrara',
            'as' => 'ejdecuenta.aprovechables.borrara']);

app/posconsumos.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class posconsumos extends Model
{
    
 protected $table="posconsumos";
   protected $fillable= ['id','nombre','pretratamiento','precio']; //

   public function oferta()
   {

return $this->belongsToMany('App\oferta')->withPivot('cantidad','precio');
    //
	}

	public function remision()
   {

return $this->belongsToMany('App\remision')->withPivot('cantidadpo');
    //
	}
}

app/Http/Controllers/Posconsumos/GeneradoresController.php
<?php

namespace App\Http\Controllers\Posconsumos;
use App\Http\Controllers\Controller;
use App\generadores;
use Illuminate\Http\Request;
use Laracasts\Flash\Flash;
use App\Imports\GeneradoresImport;
use Maatwebsite\Excel\Facades\Excel;
use App\Exports\GeneradoresExport;


class GeneradoresController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $generadores = generadores::orderBy('id','ASC')->get();

        
        return view('posconsumos.generadores.index')
        ->with('generadores', $generadores);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
         return view('posconsumos.generadores.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function import(Request $request) 
    {

        Excel::import(new GeneradoresImport,request()->file('file'));
           Flash::success(" Se han importado todos los datos de manera exitosa");
        return back();
    }

    public function export() 
    {
        return Excel::download(new GeneradoresExport, 'generadores.xlsx');
    }
}

app/Http/Controllers/Posconsumos/GestoresController.php
<?php

namespace App\Http\Controllers\Posconsumos;
use App\Http\Controllers\Controller;
use App\gestores;
use Illuminate\Http\Request;
use Laracasts\Flash\Flash;
use App\Imports\GestoresImporter;
use Maatwebsite\Excel\Facades\Excel;
use App\Exports\GestoresExport;

class GestoresController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $gestores = gestores::orderBy('id','ASC')->get();

        
        return view('posconsumos.gestores.index')
        ->with('gestores', $gestores);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('posconsumos.gestores.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $gestores = new gestores($request->all());
        $gestores->save();
        Flash::success("Se ha creado el gestor  ". $gestores->razonsocial . " de forma existosa");

        return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function import(Request $request) 
    {

        Excel::import(new GestoresImporter,request()->file('file'));
           Flash::success(" Se han importado todos los datos de manera exitosa");
        return back();
    }

    public function export() 
    {
        return Excel::download(new GestoresExport, 'gestores.xlsx');
    }
}

resources/views/posconsumos/lumina/index.blade.php
@extends('admin.template.posconsumos.main')

@section('content')

@section('titulo', 'Certificados Lumina')

<div class="row">
<div class="sticky-container">
    <ul class="sticky"  id="sticky" style="visibility: hidden;">
        <li>

            <div id="sumchecked" style="visibility: hidden; font-size: 17pt;"> <strong><span id="checked-prices-total-sum">0</span>KG </strong> </div></p>
        </li>
        
    </ul>
</div>
<div class="col-md-12">
      <div class="card">

        
        <div class="card-header">
          
        <a class="btn btn-primary btn-xs" href="{{ route('lumina.create') }}"> <i class="fa fa-plus"></i></a>

          
          
        </div>

        
          <div class="card-body">
            {!! Form::open(['route' => 'lumina.update', 'method' => 'POST']) !!}

<table id="inventario" class="datatable table table-striped">
    <thead>
                  <tr>
                      <th></th>
                      <th>REMISIÓN</th>
                      <th>PESO(KG)</th>
                      <th>FECHA DE RECEPCION</th>
                      <th>ESTADO INGRESO</th>
                      <th>ACCIÓN</th>
                  </tr>
              </thead>
    <tbody id="inventario-data">


      @foreach($certificados as $certificado)
                 <tr>

                  @if($certificado->estado_ingreso == 'POR APROVECHAR')

                  <td><input type="checkbox" name="id[]" id="" class="data-check" value="{{ $certificado->ingresos_lumina_id }}" /></td>

                  @else
                    <td><input type="checkbox" name="id[]" id="" class="data-check" value="{{ $certificado->ingresos_lumina_id }}" hidden="hidden" /></td>

                  @endif
                     <td>{{$certificado->remision}}</td>
                     <td> {{ $certificado->pesodfkg }}</td>
                     <td class="">{{$certificado->fecha_recepcion}}</td>

                     <td> @if($certificado->estado_ingreso=="POR APROVECHAR") 
                       <span class="label label-warning">{{$certificado->estado_ingreso}}</span>
                       @elseif($certificado->estado_ingreso=="APROVECHADO")
                      <span class="label label-success">{{$certificado->estado_ingreso}}</span>
                       
                    </td>
                    @endif

                    <td> @if($certificado->estado == 'ABIERTO')<a href="{{ route('lumina.edit', $certificado->ingresos_lumina_id ) }}" class="btn btn-warning btn-xs" ><span class="fa fa-pencil"> </a> 

                      @endif
                      @if($certificado->estado_ingreso == 'APROVECHADO') <a href="{{ route('lumina.pdf.generate', $certificado->ingresos_lumina_id ) }}" class="btn btn-success btn-xs" ><span class="fa fa-eye"> </a>

                        <a target="blank" href="{{ route('lumina.pdf.almc.generate', $certificado->ingresos_lumina_id ) }}" class="btn btn-primary btn-xs" ><span class="fa fa-eye"> </a>

                          <a  href="{{ route('lumina.pdf.almc.down', $certificado->ingresos_lumina_id ) }}" class="btn btn-success btn-xs" ><span class="fa fa-download"> </a>
                          @endif
                    </td>

                   
                 </tr>
               @endforeach

                  </tbody>
                  
                  
              </table>

              <div id="sumchecked" style="visibility: hidden; font-size: 25pt;"> <strong><span id="checked-prices-total-sum">0</span>KG </strong> </div><br>

              <div class="row">
                                    <div class="col-lg-12">
                                        <div class="col-xs-2">
                                             {!!Form::submit('Aprovechar y enviar', ['class' => 'btn btn-success'])!!}
                                             {!! Form::close() !!}

                                        </div>
                                    </div>
                                </div>
                             
                        </div>
                      </div>
                  </div>
              </div>


 
<!--MIERDA-->


@endsection

@section('js')

<script type="text/javascript">
  
    $(document).ready(function() {
    $("#check-all").click(function() {
        var isChecked = $(this).prop('checked');
        $(".data-check").prop('checked', isChecked);
        var $sumchecked = $('#sumchecked');
        var $totalSum = $('#checked-prices-total-sum');

        if (isChecked) {
            $totalSum.html($('#totalkg').html());
            $sumchecked.css('visibility', 'visible');
        } else {
            $totalSum.html(0);
            $sumchecked.css('visibility', 'hidden');
        }
    });

    $('#inventario-data').on('change', 'input[type="checkbox"]', function(){
        var $sumchecked = $('#sumchecked');
        var $view= $('.view');
        var $totalSum = $('#checked-prices-total-sum');
        var totalSumValue = parseFloat($totalSum.html());
        var price = parseFloat($(this).parent().next().next().html().replace(",", "."));

        if ($(this).is(':checked')) {
            totalSumValue += price;
        } else {
            totalSumValue -= price;
        }

        $totalSum.html(totalSumValue.toFixed(1));
        totalSumValue > 0 ? $sumchecked.css('visibility', 'visible') : $sumchecked.css('visibility', 'hidden');
        
        document.getElementById("sticky").style.visibility = "visible";

    });
});

// $('.chkclass').click(function() {
//         var sum = 0;
//         $('.chkclass:checked').each(function() {
//             sum += parseFloat($(this).closest('tr').find('.wagein').text());


//         });
//         $('#sum').html(sum).append('KG');

//     });



</script>
@endsection