app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/



Route::get('/', ,  function () {
    
    return view('auth.login', true);

});

Route::group(['prefix' => 'admin' ,'middleware' => 'auth'], function () {
    
   Route::resource('users','UsersController');
   Route::get('users/{id}/destroy', 
   	[ 'uses' => 'UsersController@destroy',
   	'as' => 'admin.users.destroy']);
});






Route::resource('comercial','ComercialController', ['except' => ['show']]);

 Route::resource('solicitud','SolicitudController');


   Route::group(['prefix' => 'comercial','middleware' => 'auth'], function () {
 $exitCode = Artisan::call('cache:clear');

    Route::resource('ofertasposiblesclientes','Ofertaspccontroller');
   Route::resource('creacion_de_clientes','CreacionController');
   
   Route::resource('ofertas','Ofertascontroller',['except' => ['show']]);
   Route::get('comercial/{id}/destroy', 
   	[ 'uses' => 'Ofertascontroller@destroy',
   	'as' => 'Comercial.ofertas.destroy']);
   Route::resource('clientes','ClientesController',['except' => ['show']]);

   


  



});

// Route::group(['prefix' => 'comercial' ,'middleware' => 'auth'], function () {
    
//    Route::resource('clientes','ClientesController');
//    Route::get('clientes/{identificacion}/destroy', 
//       [ 'uses' => 'ClientesController@destroy',
//       'as' => 'comercial.clientes.destroy']);
// });



    


Route::auth();

Route::get('/home', 'HomeController@index');

Route::filter('forcehttps', function()
{
  if(!Request::secure())
  {
    return Redirect::secure(Request::getRequestUri(),301);
  }
});

routes/web.php
<?php
use Illuminate\Support\Facades\Input;
use App\cliente;
use App\sedes;

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


Route::get('/', array('http', function () {

    if(Auth::guest())
    {
    return view('auth.login');
    }

    else{

    
        $identificacion = auth()->user()->identificacion;

        if (auth()->user()->type == 'cliente' && auth()->user()->lastlogin !== '0000-00-00 00:00:00') {
             auth()->user()->lastlogin = new DateTime();
            auth()->user()->save();

           return route('cliente', $identificacion);
        }

        elseif(auth()->user()->type == 'cliente'){

             auth()->user()->lastlogin = new DateTime();
        auth()->user()->save();

            Flash::warning('Por favor cambie la contraseña en la etiqueta usuarios contraseña. Muchas gracias por confiar en nosotros');    
            return route('cliente.edit', $identificacion);

        }

        if (auth()->user()->type == 'comercial') {
            return redirect('/comercial');
             auth()->user()->lastlogin = new DateTime();
            auth()->user()->save();
        }

        if (auth()->user()->type == 'gerenciaadmin') {
            return redirect ('/geradmin');
             auth()->user()->lastlogin = new DateTime();
            auth()->user()->save();
        }

        $iduser = auth()->user()->id;
        if (auth()->user()->type == 'ejdecuenta') {
            auth()->user()->lastlogin = new DateTime();
            auth()->user()->save();
           return route('ejdecuenta', $iduser);
        }

        $iduser = auth()->user()->id;
        if (auth()->user()->type == 'facturacion') {
            auth()->user()->lastlogin = new DateTime();
            auth()->user()->save();
            return redirect('/facturacion');    
        }

        $iduser = auth()->user()->id;
        if (auth()->user()->type == 'posconsumos') {
            auth()->user()->lastlogin = new DateTime();
            auth()->user()->save();
            return redirect('/pos');    
        }
   
    }

}));



Route::resource('pos','Posconsumos\PosController', ['middleware' => ['auth', 'posconsumos'],'except' => ['show']]);

Route::group(['prefix' => 'posconsumos','middleware' => ['auth', 'posconsumos']], function () {

    Route::get('/lumina/{id}/pdf', 
    [ 'uses' => 'Posconsumos\LuminaController@certpdf',
    'as' => 'lumina.pdf.generate']);

    Route::get('/lumina/almc/{id}/pdf', 
    [ 'uses' => 'Posconsumos\LuminaController@certalmcpdf',
    'as' => 'lumina.pdf.almc.generate']);

    Route::get('/lumina/almc/{id}/pdf/down', 
    [ 'uses' => 'Posconsumos\LuminaController@certalmcpdfdown',
    'as' => 'lumina.pdf.almc.down']);

    Route::get('/lumina/almc/{id}/pdf/download', 
    [ 'uses' => 'Posconsumos\LuminaController@certalmcpdfdownload',
    'as' => 'lumina.pdf.almc.generate.download']);

Route::post('import', 'Posconsumos\GestoresController@import')->name('gestores.import');


Route::post('import', 'Posconsumos\GestoresController@import')->name('gestores.import');



Route::get('export', 'Posconsumos\GestoresController@export')->name('gestores.export');

    Route::resource('lumina','Posconsumos\LuminaController');
    Route::post('lumina/update', 
    [ 'uses' => 'Posconsumos\LuminaController@update',   
    'as' => 'lumina.update']);
    

    Route::resource('generadores','Posconsumos\GeneradoresController');

    Route::get('exportgen', 'Posconsumos\GeneradoresController@export')->name('generadores.export');

    Route::post('importgen', 'Posconsumos\GeneradoresController@import')->name('generadores.import');

    Route::resource('gestores','Posconsumos\GestoresController');

    Route::get('/autocompletegen',array('as'=>'autocompletegen','uses'=>'Posconsumos\LuminaController@autocompletegen'));

    Route::get('/autocompleteges',array('as'=>'autocompleteges','uses'=>'Posconsumos\LuminaController@autocompleteges'));

    Route::get('/autocompletecanal',array('as'=>'autocompletecanal','uses'=>'Posconsumos\LuminaController@autocompletecanal'));



    });

Route::resource('facturacion','Facturacion\FacturacionController', ['middleware' => ['auth', 'facturacion'],'except' => ['show']]);
Route::group(['prefix' => 'facturacion','middleware' => ['auth', 'facturacion']], function () {

    Route::resource('remisiones','Facturacion\RemisionController', ['middleware' => ['auth', 'facturacion']]);

    Route::get('/autocompleteser',array('as'=>'facturacion.autocompleteser','uses'=>'Facturacion\RemisionController@autocompleteser'));
    Route::get('/autocompleter',array('as'=>'facturacion.autocompleter','uses'=>'Facturacion\RemisionController@autocompleter'));

    Route::get('{id}/pdf', 
    [ 'uses' => 'Facturacion\RemisionController@certpdf',
    'as' => 'cert.pdf']);

    Route::get('certpeligrosos/{id}/{identificacion}/pdf', 
    [ 'uses' => 'Facturacion\RemisionController@certpeligrosospdf',
    'as' => 'facturacion.certpeligrosospdf.pdf']);

    Route::put('certpeligrosos/{id}/upload', 
    [ 'uses' => 'Facturacion\FilescertController@store',
    'as' => 'facturacion.certpeligrosos.up']);

});


// Rutas ejdecuenta
Route::group(['prefix' => 'ejdecuenta','middleware' => ['auth', 'ejdecuenta']], function () {


    
    Route::resource('visitasejdecuenta','VisitasEjdecuentaController',['except' => ['show']]);

    Route::get('/visitas/{idvisita}', 
    [ 'uses' => 'VisitasEjdecuentaController@view',
    'as' => 'ejdecuenta.visitas.view']);

    Route::get('/{iduser}', 
    [ 'uses' => 'ejdecuenta@index',
    'as' => 'ejdecuenta']);

     Route::resource('ofertasejdecuenta','OfertasEjdecuentaController',['except' => ['show']]);

    Route::get('ofertasejdecuenta/create/{iduser}', 
    [ 'uses' => 'OfertasEjdecuentaController@create',   
    'as' => 'ofertasejdecuenta.create']); 

    Route::get('ofertasejdecuenta/index/{iduser}', 
    [ 'uses' => 'OfertasEjdecuentaController@index',   
    'as' => 'ofertasejdecuenta.index']);

    Route::get('{id}/{iduser}/pdf', 
    [ 'uses' => 'PdfControllerEjdecuenta@ofertapcpdf',
    'as' => 'ofertasejdecuenta.pdf']); 

    Route::get('{id}/{iduser}/pdf/download', 
    [ 'uses' => 'PdfControllerEjdecuenta@ofertapcpdfdownload',
    'as' => 'ofertasejdecuenta.pdf.download']);
    
    Route::get('/{id}/mail', 
    [ 'uses' => 'PdfController@mail',
    'as' => 'ofertasejdecuenta.mail']);

    Route::get('clientes/view', 
    [ 'uses' => 'ClientesEjdecuentaController@index',   
    'as' => 'clientes.ejdecuenta.index']);

    Route::get('clientes/edit/{identificacion}', 
    [ 'uses' => 'ClientesEjdecuentaController@edit',   
    'as' => 'ejdecuenta.clientes.edit']);

    Route::put('clientes/update/{identificacion}', 
    [ 'uses' => 'ClientesEjdecuentaController@update',   
    'as' => 'ejdecuenta.clientes.update']);

    Route::get('clientes/show/{identificacion}', 
    [ 'uses' => 'ClientesEjdecuentaController@show',   
    'as' => 'ejdecuenta.clientes.show']);

    Route::put('/{identificacion}/files', 
    [ 'uses' => 'CreacionController@storecomercial',
    'as' => 'ejdecuenta.clientes.files.store']);

    Route::get('clientes/sedes/{sede}/eliminar', 
    [ 'uses' => 'ClientesEjdecuentaController@borrarsede',
    'as' => 'ejdecuenta.clientes.sedes.borrar']);

    Route::post('clientes/sedes/guardar', 
    [ 'uses' => 'ClientesEjdecuentaController@save',    
    'as' => 'ejdecuenta.clientes.sedes.save']);

    Route::get('clientes/sedes/{id}/{identificacion}/editar', 
    [ 'uses' => 'ClientesEjdecuentaController@editsede',    
    'as' => 'ejdecuenta.clientes.sedes.edit']);

    

    Route::put('clientes/sedes/update/{id}/{identificacion}', 
    [ 'uses' => 'ClientesEjdecuentaController@updatesede',
    'as' => 'ejdecuenta.clientes.sedes.update']);




      Route::get('uploadedFile/{filename}',['uses' => 'CreacionController@getFile',
    'as' => 'ejdecuenta.viewfiles']);

   Route::get('uploadedFile/{filename}/delete',['uses' => 'CreacionController@deleteFile',
    'as' => 'ejdecuenta.deletefiles']);

   Route::get('uploadedFile/{filename}/residuos',['uses' => 'ResiduosController@getFile',
    'as' => 'ejdecuenta.viewfilesresiduos']);

   Route::get('uploadedFile/{filename}/residuos/delete',['uses' => 'ResiduosController@deleteFile',
    'as' => 'ejdecuenta.deletefilesresiduos']);

   Route::get('clientes/creacion/{identificacion}', 
    [ 'uses' => 'ClientesEjdecuentaController@creacion',
    'as' => 'ejdecuenta.clientes.creacion']);
   Route::put('clientes/creacion/{identificacion}/actualizar', 
    [ 'uses' => 'ClientesEjdecuentaController@up',
    'as' => 'ejdecuenta.clientes.creacion.up']);
        // Rutas edición productos

       // rutas peligrosos

         Route::resource('peligrosos','Peligrososcontroller',['except' => ['show']]);
            Route::put('{id}/peligrosos', 
            [ 'uses' => 'OfertasEjdecuentaController@peligrosos',
            'as' => 'ejdecuenta.peligrosos']);


            Route::get('peligrosos/{idoferta}/{idpeligroso}/eliminar', 
            [ 'uses' => 'OfertasEjdecuentaController@borrarp',
            'as' => 'ejdecuenta.peligrosos.borrar']);

    
            // rutas aprovechables

            Route::resource('aprovechables','Aprovechablescontroller',['except' => ['show']]);
            Route::put('{id}/aprovechables', 
            [ 'uses' => 'OfertasEjdecuentaController@aprovechables',
            'as' => 'ejdecuenta.aprovechables']);
            

            Route::get('/{idoferta}/{idaprovechables}/aprovechables/eliminar', 
            [ 'uses' => 'OfertasEjdecuentaController@borrara',
            'as' => 'ejdecuenta.aprovechables.borrara']);

app/ofertapc.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Ofertapc extends Model
{

	protected $table="ofertaspc";
   protected $fillable= ['identificacion','transporte','tipo_vehiculo','desde','hasta','tipo']; 

  public function peligroso()
   {

return $this->belongsToMany('App\peligroso')->withPivot('cantidad','observacion');

   }  //
}

resources/views/comercial/ofertapc/create.blade.php
@extends('admin.template.main')

@section('content')




  <div class="row">
    <div class="col-lg-12">
      <div class="card card-tab">
        
        <div class="card-body no-padding tab-content">
          <div role="tabpanel" class="tab-pane active" id="tab1">
            <div class="row">
              

                <div class="section">
                <div class="section-title"><i class="icon fa fa-user" aria-hidden="true"></i> Crear Ofertas Comerciales</div>
{!! Form::open(['route' => 'ofertasposiblesclientes.store', 'method' => 'POST']) !!}
               
               
               <div class="row">

    <div class="col-xs-3">


                   {!! Form::label('','')!!}
              {!!Form::number('identificacion',null, ['class' => 'form-control', 'placeholder' => 'Identificación' , 'required']) !!}
                  </div>

                  <div class="col-xs-3">

              {!! Form::label('tipo_de_identificacion','Tipo de identificación')!!}
              {!!Form::select('tipo_de_identificacion', ['Seleccione','NIT' => 'NIT','CC'=> 'CC', 'PAS' =>'PAS', 'CE' => 'CE'],null,['class' => 'form-control ', 'required'])!!}

                   </div>


                  <div class="col-xs-1">
                   {!! Form::label('','')!!}
              {!!Form::number('dv',null, ['class' => 'form-control ', 'placeholder' => 'DV' , 'required']) !!}
                  </div>

                  <div class="col-xs-5">
                   {!! Form::label('','')!!}
                   {!!Form::text('razon_social',null, ['class' => 'form-control', 'placeholder' => 'Razón social' , 'required'])!!}
                  </div>
                  <div class="col-xs-3">
                   {!! Form::label('','')!!}
                   {!!Form::text('departamento',null, ['class' => 'form-control', 'placeholder' => 'Departamento' , 'required'])!!}
                  </div>

                  <div class="col-xs-3">
                   {!! Form::label('','')!!}
                   {!!Form::text('ciudad',null, ['class' => 'form-control', 'placeholder' => 'Ciudad' , 'required'])!!}
                  </div>

                  <div class="col-xs-6">
                   {!! Form::label('','')!!}
                   {!!Form::text('direccion',null, ['class' => 'form-control', 'placeholder' => 'Dirección' , 'required'])!!}
                  </div>

                  

                  <div class="col-xs-3">
                   {!! Form::label('','')!!}
                   {!!Form::text('Nombre_contacto',null, ['class' => 'form-control', 'placeholder' => 'Nombre Contácto' , 'required'])!!}
                  </div>

                  <div class="col-xs-3">
                   {!! Form::label('','')!!}
                   {!!Form::text('Apellidos_contacto',null, ['class' => 'form-control', 'placeholder' => 'Apellidos' , 'required'])!!}
                  </div>
                  
                
                  <div class="col-xs-2">
                   {!! Form::label('','')!!}
                   {!!Form::number('Telefono_contacto',null, [  'class' => 'form-control ', 'placeholder' => 'Télefono' , 'required'])!!}
                  </div>

                  <div class="col-xs-1">
                   {!! Form::label('','')!!}
                   {!!Form::number('ext',null, ['class' => 'form-control', 'placeholder' => 'EXT' , 'required'])!!}
                  </div>

                  <div class="col-xs-3">
                   {!! Form::label('','')!!}
                   {!!Form::email('email',null, ['class' => 'form-control ', 'placeholder' => 'E- Mail' , 'required'])!!}
                  </div>

                  



               <hr>

                      

                        <h4 class="titulos">Residuos Peligrosos</h4>
                        
                <table class="table table-striped" id="tabla">
                    <thead>
                     
                      <th>Nombre de residuo</th>
                      



                    </thead>

                    <tbody>
                        


                    <tr>
                        

             

                     
                         
                       
                         
                         
                         

                    </tr>


                    <tr  class="fila" >
                        
                     <td> {!!Form::select('nombre2 []',$peligrosos,null,[ 'id'=>'oculto', 'class' => 'form-control select-residuos .col-md-4'])!!}</td>
                      

                         
                       
                         
                         
                         <td class="eliminar btn btn-warning btn-xs">Eliminar</td>

                    </tr>

                       

                         
              



                    </tbody>
                </table>

                <td><input type="button" id="agregar" value="Agregar fila" class="btn btn-success btn-xs"/></a></td>
                    





                  <div class="col-xs-2">
                   {!!Form::submit('Crear', ['class' => 'btn btn-primary'])!!}
                  </div>




                  
</div>




              

                

                
              
                
</div>
  
   </div>
   </div>
   </div>
   </div>
   </div>
   </div>

                  

          
          
@endsection

@section('js')



 <!-- Jquery -->
<script type="text/javascript" src="{{asset('//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js')}}"></script>
<script type="text/javascript" src="{{asset('//ajax.googleapis.com/ajax/libs/jqueryui/1.10.2/jquery-ui.min.js')}}"></script>
<script src="{{asset('plugins/chosen/chosen.jquery.js')}}"></script>
<link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet">
<script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.16.0/jquery.validate.min.js"></script>



<script type="text/javascript" src="{{asset('plugins/bootstrap/assets/js/funciones.js')}}"></script> 
<script type="text/javascript" src="{{asset('plugins/bootstrap/assets/js/sweetalert.min.js')}}"></script>
<script src="{{asset('plugins/chosen/chosen.jquery.js')}}"></script>

<script>
  

   
jQuery(function($){
  
  $('.select-transporte').chosen({


    no_results_text: "Su busqueda no arroja resultados",
    
    width: '90%',

  });
});

jQuery(function($){
  
  $('.select-residuos').chosen({


    no_results_text: "Su busqueda no arroja resultados",
    
    width: '80%',

  });
});
</script>

@endsection

resources/views/comercial/ofertapc/index.blade.php
 

@section('content')

@section('titulo')
Ofertas Comerciales

@endsection


@extends('admin.template.main')

@section('content')

@section('titulo')
<div class="title">Hola, {{ Auth::user()->name }}</div>
@endsection
<div class="row">
  <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
      <a class="card card-banner card-green-light">
  <div class="card-body">
    <i class="icon fa fa-shopping-basket fa-4x"></i>
    <div class="content">
      <div class="title">Numero de ofertas</div>
      <div class="value"><span class="sign">{{ $ofertas }}</span></div>
    </div>
  </div>
</a>

  </div>
  <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
      <a class="card card-banner card-blue-light">
  <div class="card-body">
    <i class="icon fa fa-thumbs-o-up fa-4x"></i>
    <div class="content">
      <div class="title">clientes</div>
      <div class="value"><span class="sign"></span>{{ $clientes }}</div>
    </div>
  </div>
</a>

  </div>
  <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
      <a class="card card-banner card-yellow-light">
  <div class="card-body">
    <i class="icon fa fa-user-plus fa-4x"></i>
    <div class="content">
      <div class="title">New Registration</div>
      <div class="value"><span class="sign"></span>50</div>
    </div>
  </div>
</a>

  </div>
</div>



<div class="row">
  <div class=" col-md-12">
    <div class="card card-mini">
      <div class="card-header">
        <div class="card-title">Ofertas Recientes</div>
        <ul class="card-action">
          <li>
            <a href="/">
              <i class="fa fa-refresh"></i>
            </a>
          </li>
        </ul>
      </div>
      <div class="card-body no-padding table-responsive">
        <table class="table card-table">



          <thead>

         
            <tr>
            <th>ID</th>
              <th>EMPRESA</th>
              <th>TIPO</th>
              <th>ESTADO</th>
              <th>ACCIÓN</th>
            </tr>
          </thead>

         
          <tbody>


           
            @foreach($ofertasc as $oferta)
              

            <tr>
          
           <td> {{$oferta->id}}</td> 
           
          
                         
           <td> {{$oferta->razon_social}}</td>
           
           <td> {{$oferta->tipo}}</td> 
       
           

           <td> @if($oferta->Estado=="En espera") 
   <span class="label label-warning">{{$oferta->Estado}}</span>

  

   
   @else
<span class="label label-primary">{{$oferta->Estado}}</span>
   @endif</td>


    <td> <a href="{{route('ofertas.edit' , $oferta->id )}}" class="btn btn-warning btn-xs" ><span class="fa fa-pencil"> </a> <a href="{{route('ofertas.pdf' , $ofertapc->id )}}" target="_blank" class="btn btn-success btn-xs" ><span class="fa fa-eye"> </a> <a href="{{route('ofertas.pdf.download' , $oferta->id )}}" target="_blank" class="btn btn-primary btn-xs" ><span class="fa fa-arrow-down"> </a></td>

      </tr>
      
   @endforeach

   
          </tbody>

          
        </table>
        
      </div>
    </div>






  </div>


  


@endsection